version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8888:8000"
    volumes:
      - .:/app
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
